# Generated by Django 5.1 on 2025-01-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_postimage_options_alter_posttext_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='posttext',
            options={},
        ),
    ]
