# Generated by Django 5.1 on 2025-01-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_postimage_options_alter_posttext_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='posttext',
            name='order',
        ),
    ]
