# Generated by Django 5.1 on 2025-01-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_post_author',
        ),
    ]
