# Generated by Django 5.1 on 2025-01-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_comment_is_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_post_author',
            field=models.BooleanField(default=False),
        ),
    ]
