# Generated by Django 5.1 on 2025-02-03 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_is_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbor_visibility',
            field=models.BooleanField(default=True, help_text='서로이웃 목록을 공개할지 여부'),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbors',
            field=models.ManyToManyField(blank=True, related_name='neighbor_profiles', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Unnamed', max_length=15),
        ),
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '신청중'), ('accepted', '수락됨'), ('rejected', '거절됨')], default='pending', max_length=20)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_neighbor_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_neighbor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
