# Generated by Django 5.1 on 2025-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_neighbor_visibility_profile_neighbors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='urlname',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='urlname_edit_count',
            field=models.PositiveIntegerField(default=0, help_text='urlname 변경 횟수 (0: 변경 가능, 1: 변경 불가)'),
        ),
    ]
