# Generated by Django 5.1 on 2025-02-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_profile_urlname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbors',
            field=models.ManyToManyField(blank=True, to='main.profile'),
        ),
    ]
