# Generated by Django 5.1 on 2025-02-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profile_neighbors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='작성 상태'),
        ),
    ]
