# Generated by Django 5.1 on 2025-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_posttext_font_posttext_font_size_posttext_is_bold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttext',
            name='font',
            field=models.CharField(choices=[('nanum_gothic', '나눔고딕'), ('Noto Serif Korean', 'Noto Serif Korean'), ('Gaegu', 'Gaegu'), ('Nanum Pen Script', 'Nanum Pen Script'), ('Black And White Picture', 'Black And White Picture')], default='nanum_gothic', max_length=25),
        ),
    ]
