# Generated by Django 5.1 on 2025-02-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_post_subject_category_alter_post_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subject_category',
            new_name='keyword',
        ),
    ]
