# Generated by Django 5.1 on 2025-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
