# Generated by Django 5.1 on 2025-02-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_comment_is_read_post_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
