# Generated by Django 5.1.6 on 2025-02-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': '아이디가 중복되었습니다. 다시 입력해주세요.'}, max_length=100, unique=True)),
            ],
        ),
    ]
