# Generated by Django 5.1.6 on 2025-02-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(error_messages={'unique': '아이디가 중복되었습니다. 다시 입력해주세요.'}, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
